#54 recent 관련 코드 수정
soyoungjeong/EmojiByEternal pull request #58
Opened 2020-10-01 07:13 UTC by sewonkimm

- commit template 추가했습니다.
- 클릭한 emoji를 localStorage에 추가하는 함수 이름을 store에서 updateRecent로 변경했습니다.
- updateRecent 함수 내부에 renderRecent 함수를 실행하도록 하여 autoCopyOn, autoCopyOff에서 renderRecent를 실행하지 않도록 했습니다.
- 그 외 eslint 수정으로 잡힌 문법적인 사항들 수정했습니다.

---

Q . recent 동작 관련 js 코드는 recent 폴더에 있는데 이 폴더가 events 폴더에 들어가는게 적절할까요...?

2020-10-01 14:35 UTC, soyoungjeong requested changes
recent에 있는 동작은 addEventListner를 해준 것은 아니라 recent에 있는 것이 적절해보입니다ㅎㅎ removeDuplicate의 내용이 간소화되면 recent 폴더에 있는 것도 좋을 것 같아요!

2020-10-01 14:35 UTC, soyoungjeong commented on js/init.js
> +  if (localStorage.getItem('firstLoad') === null) {
처음 다운로드 받은 유저는 firstLoad가 undefined가 됩니다ㅎㅎ == null 을 할 경우 undefined와 null인 경우를 동시에 체크할 수 있어 좋습니다😀

2020-10-01 14:35 UTC, soyoungjeong commented on js/recent/updateRecent.js
>  import removeDuplicate from '../service/removeDuplicate.mjs';
removeDuplicate 파일은 그냥 js 파일이어도 괜찮을 것 같아요!

2020-10-01 14:35 UTC, soyoungjeong commented on js/service/removeDuplicate.mjs
>              break;
파일의 for문 안에 구문들의 depth가 깊어 가독성이 안좋아 줄이는 방법을 생각해보면 좋을 것 같습니다 : )

2020-10-01 14:35 UTC, soyoungjeong commented on js/service/removeDuplicate.mjs
>        tempArr.push(arr[i]);
이쪽에 continue; 를 사용해주면 else를 사용하지 않아도 될 것 같아요 !

2020-10-01 14:35 UTC, soyoungjeong commented on js/service/removeDuplicate.mjs
>              break;
filter, includes, some 등의 함수들을 활용해보면 어떨까요???

2020-10-01 14:35 UTC, soyoungjeong commented on js/recent/renderRecent.js
>    if (recent !== null) {
이부분은 if(recent === null) return 으로 early return 을 해주면 depth를 줄일 수 있어 보입니다ㅎㅎ https://code-200.tistory.com/14 이 포스트에 잘 나와있는 것 같아요!

2020-10-01 14:35 UTC, soyoungjeong commented on js/events/buttonEvent/recentSetting.js
recent를 다른 숫자로 변경했을 때도 renderRecent()가 필요해보입니다. 실행했더니 아무 동작도 안일어나네요!

2020-10-02 04:35 UTC, sewonkimm commented on js/init.js
> +  if (localStorage.getItem('firstLoad') === null) {
![image](https://user-images.githubusercontent.com/30452963/94888454-236e7d00-04b4-11eb-974a-91e0c5acef78.png)

null로 확인됩니다!

2020-10-02 06:03 UTC, sewonkimm commented on js/recent/renderRecent.js
>    if (recent !== null) {
좋은 의견 감사합니다! 앞으로 Depth 줄이는 것에 좀 더 신경써 보겠습니다 ㅎㅎ

2020-10-02 06:08 UTC, soyoungjeong commented on js/init.js
> +  if (localStorage.getItem('firstLoad') === null) {
앗 그러네요 ㅎㅎ

2020-10-02 06:19 UTC, soyoungjeong approved these changes
변수명만 변경해서 merge해주세요!!

2020-10-02 06:19 UTC, soyoungjeong commented on js/init.js
> +    localStorage.setItem('firstLoad', true);
변수명으로 hasInitialSetting은 어떠신가요??

2020-10-02 06:19 UTC, soyoungjeong commented on js/service/removeDuplicate.js
> +}
전에 코드보다 좋은 것 같아요👍🏻👍🏻

2020-10-02 06:23 UTC, merged